### ISSUE TITLE
Consider switching to ➕ and ➖ for positive/negative for better accessibility

### ISSUE THREAD

**Issue by waded** [olivierlacan/traceur#3]
The 🔴 and 🟢 used for positive/negative test result are hard to differentiate for some people.

Also, in Excel on Windows 16.0.13001.20254 (I think perhaps not Excel Mac, or Excel web/mobile), emoji are black and white. Not completely impossible to tell apart, but not intuitive either:

![image](https://user-images.githubusercontent.com/1535656/88237847-6521b280-cc3d-11ea-9655-d1f0f144b244.png)

For both these reasons ➕ and ➖  could be better.

**Comment by olivierlacan** [comment]
Yeah this doesn't happen on Excel 16.39 for Mac. 
![image](https://user-images.githubusercontent.com/65950/88238411-999e6a00-cc4f-11ea-869c-e7761d8210b6.png)

**Comment by waded** [comment]
The color-blindness concern isn't Excel or OS-specific. 😉

**Comment by olivierlacan** [comment]
@waded See 692a80f 😛
